# Generated by Django 4.0.6 on 2022-08-18 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('WAITING_FOR_RECEIPT', '접수 대기'), ('RECEIPT_COMPLETE', '접수 완료'), ('DELIVERY', '배달 중'), ('DELIVERY_COMPLETE', '배달 완료')], default='WAITING_FOR_RECEIPT', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('CASH', '현금결제'), ('CREDIT_CARD', '카드결제'), ('TRANSFER', '계좌이체')], max_length=20)),
                ('total_price', models.PositiveIntegerField()),
                ('month_total_price', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurantapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu', to='orderapp.order')),
            ],
        ),
    ]
